print("\t-----------------------------------------------------------------")
print("\t|\t| BISMILLAH SUPERMARKET\t\t\t\t\t|")
print("\t|\t\t\t\t\t\t\t\t|")
print("\t|NAME:\t\tRashidah Abbas\t\t\t\t\t|")
print("\t|EMAIL:\t\trasidahabbas01@gmail.com\t\t\t|")
print("\t|ACTIVITIES:\t\tsupermarket and restuarant\t\t|")
print("\t|TIME:\t\t open from 7:00am-12am\t\t\t\t|")
print("\t|LOCATION:\tEntebbe road Rana building opp shell station\t|")
print("\t|\t\tEVERYDAY 24/7\t\t\t\t\t|")
print("\t|ITEMS:\t\tfood,clothes jewellies,etc\t\t\t|")
print("\t|ContaCT US:\t\t0753017584/0743752457\t\t\t|")
print("\t|\t\t\tCOME ONE COME ALL\t\t\t|")
print("\t-----------------------------------------------------------------")
      
